from kitti_model_config import kitti_model_config
from kitti_vgg16_config import kitti_vgg16_config
from kitti_res50_config import kitti_res50_config
from kitti_squeezeDet_config import kitti_squeezeDet_config
from kitti_squeezeDetPlus_config import kitti_squeezeDetPlus_config
from nexarear_squeezeDet_config import nexarear_squeezeDet_config
from nexarear_squeezeDetPlus_config import nexarear_squeezeDetPlus_config
from nexarear_res50_config import nexarear_res50_config

